version: '3.8'

services:
  django:
    build:
      context: ./django_project
      dockerfile: Dockerfile
    image: wafa003/back-end
    ports:
      - "8000:8000"
    volumes:
      - django_data:/app/db.sqlite3  # Persist the SQLite database file
    
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend/risk/modernize-react-lite/package
      dockerfile: Dockerfile
    image: wafa003/front-end
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/risk/modernize-react-lite/package:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
