name: Build and Push Docker Images

on:
  push:
    branches:
      - main # Adjust this to your main development branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    # Build and push backend image
    - name: Build and push Django backend image
      run: |
        docker build -t wafa003/back-end:latest ./django_project
        docker push wafa003/back-end:latest

    # Build and push frontend image
    - name: Build and push React frontend image
      run: |
        docker build -t wafa003/front-end:latest ./frontend/risk/modernize-react-lite/package
        docker push wafa003/front-end:latest
    
    