name: CD Pipeline

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Pull Docker image front end
      run: sudo docker pull wafa003/front-end:latest

    - name: Delete Old Docker Container
      run: sudo docker rm -f frontend-container || true

    - name: Run Docker Container
      run: sudo docker run -d -p 5173:5173 --name frontend-container wafa003/front-end


    - name: Pull Docker image backend 
      run: sudo docker pull wafa003/back-end:latest

    - name: Delete Old Docker Container
      run: sudo docker rm -f backend-container || true

    - name: Run Docker Container
      run: sudo docker run -d -p 8000:8000 --name backend-container wafa003/back-end
